Edit Displayed Text in Bug List Filters Fix
Niloth-p/glitch-guru pull request #13
Opened 2023-11-16 13:20 UTC by harsha-mangena

- issue https://github.com/Niloth-p/glitch-guru/issues/1
- used constants for the text displayed in filters

2023-11-17 19:41 UTC, Niloth-p requested changes
Those (the choices) are not dictionaries.
I recommend you to setup the project locally and run the server with your changes so that you can debug syntax errors like this on your own.

2023-11-18 06:38 UTC, harsha-mangena commented
@Niloth-p 
I kind of assumed assumed those were dictionaries.
Added util function for getting the actual text from the list.

2023-11-24 16:56 UTC, harsha-mangena commented
@Niloth-p  Can you kindly review this, And please let me know If any changes are required.

2023-11-25 10:22 UTC, Niloth-p approved these changes

2023-11-25 10:24 UTC, merged